name: Website Test & Alert

on:
  schedule:
    - cron: "*/5 * * * *"   # every 10 minutes
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Mask Gmail
        run: echo "::add-mask::${{ secrets.EMAIL_USER }}"

      - name: Test multiple endpoints
        run: |
          ENDPOINTS=(
            "https://nexus-ai-1s8u.onrender.com/"
            "https://nexus-ai-1s8u.onrender.com/api"
            "https://nexus-ai-1s8u.onrender.com/health"
          )

          ERRORS=0
          for URL in "${ENDPOINTS[@]}"; do
            STATUS=$(curl -o /dev/null -s -w "%{http_code}" "$URL")
            if [ "$STATUS" -ne 200 ]; then
              echo "❌ $URL is DOWN (status $STATUS)" >> result.log
              ERRORS=1
            else
              echo "✅ $URL is UP (status $STATUS)"
            fi
          done

          if [ $ERRORS -ne 0 ]; then
            exit 1
          fi

      - name: Send email if failed
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: "🚨 Website Down Alert"
          to: hello.connectsphere.official@gmail.com
          from: "Uptime Bot <${{ secrets.EMAIL_USER }}>"
          body: |
            One or more endpoints are DOWN:

            $(cat result.log)

            Please check your backend immediately.
